{% set name = "wagtail-cache" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coderedcorp/wagtail-cache/archive/v{{ version }}.tar.gz
  sha256: cbf3bec8f2457cdc6632bbc2b7746f4506f5cb2f196fe06384490c3b49901baa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - wagtail >=3.0,<7

test:
  imports:
    - wagtailcache
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coderedcorp/wagtail-cache
  summary: A simple page cache for Wagtail based on the Django cache middleware.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
